version: '3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    ports:
      - '${DATABASE_PORT}:3306'
    networks:
      - recipe
    restart: always

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '${CACHE_PORT}:6379'
    volumes:
      - ./recipe-redis/conf:/usr/local/etc/redis/redis.conf
    networks:
      - recipe
    restart: always

networks:
  recipe:
